// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmW2AiKIAW-ROlnQ1Ym-DHrYv0k1w9lTo',
    appId: '1:996455173249:web:acbc6d47a4c412e5889180',
    messagingSenderId: '996455173249',
    projectId: 'dalelapp-b090e',
    authDomain: 'dalelapp-b090e.firebaseapp.com',
    storageBucket: 'dalelapp-b090e.appspot.com',
    measurementId: 'G-K1REEXY6S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRUxBn4Xmc4RNgxqXKBb9yALUCSBgp6k',
    appId: '1:996455173249:android:ce0e744e8ef17f4f889180',
    messagingSenderId: '996455173249',
    projectId: 'dalelapp-b090e',
    storageBucket: 'dalelapp-b090e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwGkFwhHfJnuPNo192fT--I_rgr3lnxuQ',
    appId: '1:996455173249:ios:d6ce1e91d7335295889180',
    messagingSenderId: '996455173249',
    projectId: 'dalelapp-b090e',
    storageBucket: 'dalelapp-b090e.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwGkFwhHfJnuPNo192fT--I_rgr3lnxuQ',
    appId: '1:996455173249:ios:d6ce1e91d7335295889180',
    messagingSenderId: '996455173249',
    projectId: 'dalelapp-b090e',
    storageBucket: 'dalelapp-b090e.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmW2AiKIAW-ROlnQ1Ym-DHrYv0k1w9lTo',
    appId: '1:996455173249:web:ada152d65ce54bd0889180',
    messagingSenderId: '996455173249',
    projectId: 'dalelapp-b090e',
    authDomain: 'dalelapp-b090e.firebaseapp.com',
    storageBucket: 'dalelapp-b090e.appspot.com',
    measurementId: 'G-X1JYPQ43K6',
  );
}
