// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16RSBLRtfgvmxD3a8J7u5pUJ5e0qYKsI',
    appId: '1:705177514166:web:f941e043f05180bba97617',
    messagingSenderId: '705177514166',
    projectId: 'dalelapp-bf77f',
    authDomain: 'dalelapp-bf77f.firebaseapp.com',
    storageBucket: 'dalelapp-bf77f.appspot.com',
    measurementId: 'G-FM5KRZZ275',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjIfWvYYAx7O9HIfHp5C9NOy8-qTgeYDo',
    appId: '1:705177514166:android:49e2412a48b351cca97617',
    messagingSenderId: '705177514166',
    projectId: 'dalelapp-bf77f',
    storageBucket: 'dalelapp-bf77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1CvNGXOqX_ZlND12Lqdi-AYSt_eTTfE',
    appId: '1:705177514166:ios:4d3844a1fd186ad5a97617',
    messagingSenderId: '705177514166',
    projectId: 'dalelapp-bf77f',
    storageBucket: 'dalelapp-bf77f.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1CvNGXOqX_ZlND12Lqdi-AYSt_eTTfE',
    appId: '1:705177514166:ios:4d3844a1fd186ad5a97617',
    messagingSenderId: '705177514166',
    projectId: 'dalelapp-bf77f',
    storageBucket: 'dalelapp-bf77f.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16RSBLRtfgvmxD3a8J7u5pUJ5e0qYKsI',
    appId: '1:705177514166:web:612775e7a00a9baaa97617',
    messagingSenderId: '705177514166',
    projectId: 'dalelapp-bf77f',
    authDomain: 'dalelapp-bf77f.firebaseapp.com',
    storageBucket: 'dalelapp-bf77f.appspot.com',
    measurementId: 'G-JRR3J7YDC4',
  );
}
